add helpers to communicate progress

diff --git a/install b/install
--- a/install
+++ b/install
@@ -2,15 +2,40 @@ set -Eeuo pipefail
 
 : ${DOTFILES_PATH:="$HOME/dotfiles"}
 
+info() {
+  printf "\r  [ \033[00;34m..\033[0m ] $1\n"
+}
+
+user() {
+  printf "\r  [ \033[0;33m??\033[0m ] $1\n"
+}
+
+success() {
+  printf "\r\033[2K  [ \033[00;32mOK\033[0m ] $1\n"
+}
+
+fail() {
+  printf "\r\033[2K  [\033[0;31mFAIL\033[0m] $1\n"
+  echo ''
+  exit 1
+}
+
 check_os() {
+  info 'Checking operating system...'
   if [ "$(uname -s)" != "Darwin" ]; then
-    echo "These dotfiles require MacOS"
-    exit 1
+    fail 'These dotfiles require MacOS'
+  else
+    success 'Operating system ok'
   fi
 }
 
+provision_configs() {
+  info 'Start provisioning configuration files'
+}
+
 main() {
-    check_os
+  check_os
+  provision_configs
 }
 
 main
